import { TangoEvent } from './types';

// Helper to calculate date offsets relative to today (defaulting to 2026-09-05 or current real date)
export function getDateOffset(days: number): string {
  const base = new Date();
  base.setDate(base.getDate() + days);
  return base.toISOString().split('T')[0];
}

// Initial curated tango events across world tango hubs
export const INITIAL_EVENTS: TangoEvent[] = [
  {
    id: "evt_atlanta_2026",
    event_name: "Atlanta Tango Marathon",
    event_type: "MARATHON",
    start_date: "2026-10-15",
    end_date: "2026-10-18",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Westin Buckhead, 3391 Peachtree Rd NE",
    price: "$165",
    is_free: false,
    source_url: "https://atlantatangomarathon.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-01T12:00:00Z",
    notes: "Role-balanced marathon, 300 dancers capacity, wooden dance floor."
  },
  {
    id: "evt_tp_ljubljana_fest_2026",
    event_name: "Ljubljana Tango Festival 2026 (20th Edition)",
    event_type: "FESTIVAL",
    start_date: "2026-11-12",
    end_date: "2026-11-15",
    city: "Ljubljana",
    country_code: "SI",
    address: "Grand Hotel Union Hall & Studio Moj korak, Miklošičeva cesta 1",
    price: "€180",
    is_free: false,
    source_url: "https://www.facebook.com/groups/115408145174568",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Popular FB Group",
    created_at: "2026-09-06T00:00:00Z",
    notes: "20th Anniversary milestone edition. 4 days of grand evening milongas with live tango orchestra, world-class maestros, and buena onda spirit."
  },
  {
    id: "evt_tp_crossroads_marathon",
    event_name: "Crossroads Tango Marathon 2026 Autumn Edition",
    event_type: "MARATHON",
    start_date: "2026-10-16",
    end_date: "2026-10-18",
    city: "Ljubljana",
    country_code: "SI",
    address: "Ljubljana Puppet Theatre (Lutkovno gledališče), Krekov trg 2",
    price: "€140",
    is_free: false,
    source_url: "https://www.facebook.com/groups/115408145174568",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Popular FB Group",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Role-balanced autumn marathon for 250 international dancers in historic theatrical hall with supreme acoustics."
  },
  {
    id: "evt_tp_la_milonguita_mensual",
    event_name: "La Milonguita Mensual at Studio Moj Korak",
    event_type: "MILONGA",
    start_date: "2026-10-03",
    end_date: "2026-10-03",
    city: "Ljubljana",
    country_code: "SI",
    address: "Studio Moj korak, Vilharjeva cesta 3",
    price: "€12",
    is_free: false,
    source_url: "https://www.facebook.com/groups/115408145174568",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Popular FB Group",
    created_at: "2026-09-06T00:00:00Z",
    notes: "10th season opening monthly milonga. Traditional tandas with cortinas, friendly embrace, and complimentary refreshments."
  },
  {
    id: "evt_tp_corazon_de_ljubljana",
    event_name: "Corazon de Ljubljana Tango Gala & Milonga",
    event_type: "FESTIVAL",
    start_date: "2026-09-25",
    end_date: "2026-09-27",
    city: "Ljubljana",
    country_code: "SI",
    address: "Festival Hall Ljubljana (Festivalna dvorana), Vilharjeva cesta 11",
    price: "€95",
    is_free: false,
    source_url: "https://www.facebook.com/groups/115408145174568",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Popular FB Group",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Autumn gala weekend featuring live concert, guest maestro masterclasses, and three evening social milongas."
  },
  {
    id: "evt_tp_milonga_diferente",
    event_name: "Milonga Diferente Sunday Social",
    event_type: "MILONGA",
    start_date: "2026-09-27",
    end_date: "2026-09-27",
    city: "Ljubljana",
    country_code: "SI",
    address: "Klub CD (Cankarjev dom), Prešernova cesta 10",
    price: "€10",
    is_free: false,
    source_url: "https://www.facebook.com/groups/115408145174568",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Popular FB Group",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Sunday evening cozy social milonga with eclectic traditional selection, warm welcoming ambiance, and great acoustics."
  },
  {
    id: "evt_tangobar_ats_2nd_fri",
    event_name: "Atlanta Tango Social 2nd Friday Milonga",
    event_type: "MILONGA",
    start_date: "2026-09-11",
    end_date: "2026-09-11",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Academy Ballroom Atlanta, 800 Miami Cir NE #140",
    price: "$15",
    is_free: false,
    source_url: "https://www.facebook.com/groups/tangobaratlanta",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Bar Atlanta",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Monthly 2nd Friday milonga from 8:00 PM to 11:30 PM. Warm embrace, welcoming community, and traditional Golden Age tandas."
  },
  {
    id: "evt_tangobar_salvo_rossi",
    event_name: "ATS Anniversary Weekend with José Luis Salvo & Carla Rossi",
    event_type: "FESTIVAL",
    start_date: "2026-10-09",
    end_date: "2026-10-11",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Academy Ballroom Atlanta, 800 Miami Cir NE #140",
    price: "$120",
    is_free: false,
    source_url: "https://www.facebook.com/groups/tangobaratlanta",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Bar Atlanta",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Special anniversary tango weekend featuring Argentine Tango World Champions José Luis Salvo & Carla Rossi. Workshops and gala milongas."
  },
  {
    id: "evt_tangobar_milonga_azul",
    event_name: "Milonga Azul at Dance It Off Studio",
    event_type: "MILONGA",
    start_date: "2026-09-19",
    end_date: "2026-09-19",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Dance It Off Studio, 6080 Sandy Springs Circle",
    price: "$15",
    is_free: false,
    source_url: "https://www.facebook.com/groups/tangobaratlanta",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Bar Atlanta",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Regular 3rd Saturday Milonga from 9:00 PM to midnight. Excellent wooden floor, light refreshments, and authentic tandas."
  },
  {
    id: "evt_tangobar_tango_lounge",
    event_name: "The Tango Lounge Sunday Milonga",
    event_type: "MILONGA",
    start_date: "2026-09-20",
    end_date: "2026-09-20",
    city: "Roswell",
    state: "GA",
    country_code: "US",
    address: "Ballroom Impact, 1425 Market Blvd, Suite 525",
    price: "$15",
    is_free: false,
    source_url: "https://www.facebook.com/groups/tangobaratlanta",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Bar Atlanta",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Weekly Sunday milonga with complimentary pre-milonga class at 6:30 PM. Active Atlanta tango community social."
  },
  {
    id: "evt_tangobar_southern_holiday",
    event_name: "Southern Holiday Tango Fest 2026",
    event_type: "FESTIVAL",
    start_date: "2026-12-17",
    end_date: "2026-12-20",
    city: "Norcross",
    state: "GA",
    country_code: "US",
    address: "Norcross Cultural Arts & Community Center, 10 College St NW",
    price: "$180",
    is_free: false,
    source_url: "https://www.facebook.com/groups/tangobaratlanta",
    source_type: "FACEBOOK",
    status: "APPROVED",
    submitted_by: "Tango Bar Atlanta",
    created_at: "2026-09-06T00:00:00Z",
    notes: "Annual 4-day winter celebration in Greater Atlanta. Outstanding guest DJs, international social dancers, and festive milongas."
  },
  {
    id: "evt_buenos_aires_citas",
    event_name: "CITA Tango Festival 2026",
    event_type: "FESTIVAL",
    start_date: "2026-11-05",
    end_date: "2026-11-11",
    city: "Buenos Aires",
    state: "CABA",
    country_code: "AR",
    address: "Palacio San Miguel, Suipacha 84",
    price: "$280",
    is_free: false,
    source_url: "https://citadancefestival.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-02T10:00:00Z",
    notes: "International festival with top Argentine maestros, live orchestras, masterclasses."
  },
  {
    id: "evt_seoul_tango_encuentro",
    event_name: "Seoul Autumn Tango Encuentro",
    event_type: "ENCUENTRO",
    start_date: "2026-10-23",
    end_date: "2026-10-25",
    city: "Seoul",
    state: "Gangnam",
    country_code: "KR",
    address: "El Tango Studio, Nonhyeon-dong 142-3",
    price: "₩180,000",
    is_free: false,
    source_url: "https://tangoencuentroseoul.kr",
    source_type: "MANUAL",
    status: "APPROVED",
    submitted_by: "admin",
    created_at: "2026-09-03T08:00:00Z",
    notes: "Milonguero style abrazo cerrado, mirada y cabeceo tradition observed."
  },
  {
    id: "evt_berlin_festival",
    event_name: "Berlin Tango High Festival",
    event_type: "FESTIVAL",
    start_date: "2026-11-20",
    end_date: "2026-11-24",
    city: "Berlin",
    state: "Berlin",
    country_code: "DE",
    address: "Bebop Ballroom, Pfuelstraße 5",
    price: "€210",
    is_free: false,
    source_url: "https://berlintangofestival.de",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-03T15:00:00Z",
    notes: "5 days of workshops, afternoon and night milongas overlooking the Spree."
  },
  {
    id: "evt_barcelona_milonguero",
    event_name: "Barcelona Mar y Tango Marathon",
    event_type: "MARATHON",
    start_date: "2026-12-04",
    end_date: "2026-12-07",
    city: "Barcelona",
    state: "Catalonia",
    country_code: "ES",
    address: "La Nau Cultural Center, Carrer de la Selva de Mar 46",
    price: "€140",
    is_free: false,
    source_url: "https://barcelonatangomarathon.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-04T09:00:00Z",
    notes: "Winter seaside marathon with international DJs and hot chocolate."
  },
  {
    id: "evt_tokyo_sakura_winter",
    event_name: "Tokyo Ginza Gran Milonga",
    event_type: "MILONGA",
    start_date: "2026-09-26",
    end_date: "2026-09-26",
    city: "Tokyo",
    state: "Tokyo",
    country_code: "JP",
    address: "Ginza Hall, 6-10-1 Ginza, Chuo City",
    price: "¥3,500",
    is_free: false,
    source_url: "https://tokyotango.jp/ginza",
    source_type: "MANUAL",
    status: "APPROVED",
    submitted_by: "user_dancer",
    created_at: "2026-09-04T11:00:00Z",
    notes: "Premier Saturday milonga in the heart of Ginza with guest DJ from Buenos Aires."
  },
  {
    id: "evt_rome_autumn_encuentro",
    event_name: "Roma Dolce Vita Encuentro",
    event_type: "ENCUENTRO",
    start_date: "2026-10-09",
    end_date: "2026-10-12",
    city: "Rome",
    state: "Lazio",
    country_code: "IT",
    address: "Teatro San Genesio, Via Podgora 1",
    price: "€175",
    is_free: false,
    source_url: "https://romatangoencuentro.it",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-04T14:00:00Z",
    notes: "Encuentro milonguero in central Rome, strictly traditional tandas."
  },
  {
    id: "evt_paris_free_open_air",
    event_name: "Paris Seine River Open-Air Milonga",
    event_type: "MILONGA",
    start_date: "2026-09-19",
    end_date: "2026-09-19",
    city: "Paris",
    state: "Île-de-France",
    country_code: "FR",
    address: "Quai Saint-Bernard Amphi 1, Jardin Tino-Rossi",
    price: "Free",
    is_free: true,
    source_url: "https://paristango.org/arenes",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-05T08:00:00Z",
    notes: "Iconic open air sunset milonga on the banks of Seine river. Free admission."
  },
  {
    id: "evt_new_york_winter_fest",
    event_name: "New York Tango Winter Congress",
    event_type: "FESTIVAL",
    start_date: "2027-01-14",
    end_date: "2027-01-18",
    city: "New York",
    state: "NY",
    country_code: "US",
    address: "Midtown Manhattan Ballroom, 450 7th Ave",
    price: "$240",
    is_free: false,
    source_url: "https://newyorktangocongress.org",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-05T09:00:00Z",
    notes: "MLK weekend 4-day festival with international orchestra and master workshops."
  },
  {
    id: "evt_pending_madrid_sample",
    event_name: "Madrid Corazón de Tango Marathon",
    event_type: "MARATHON",
    start_date: "2026-11-27",
    end_date: "2026-11-29",
    city: "Madrid",
    state: "Community of Madrid",
    country_code: "ES",
    address: "Gran Vía Theater Hall, C. Gran Vía 54",
    price: "€130",
    is_free: false,
    source_url: "https://madridtangomarathon.es",
    source_type: "MANUAL",
    status: "PENDING",
    submitted_by: "organizer_carlos",
    submitted_by_name: "Carlos Mendez",
    created_at: "2026-09-05T18:00:00Z",
    notes: "Awaiting admin verification of venue certificate and website."
  },
  // --- US Cities Milongas ---
  {
    id: "evt_nyc_milonga_rosa",
    event_name: "Milonga Rosa Central NYC",
    event_type: "MILONGA",
    start_date: "2026-10-10",
    end_date: "2026-10-10",
    city: "New York",
    state: "NY",
    country_code: "US",
    address: "Stepping Out Studios, 37 W 26th St, 9th Floor",
    price: "$25",
    is_free: false,
    source_url: "https://milongarosa.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:00:00Z",
    notes: "Premier Saturday night Manhattan milonga with live guest musicians and traditional tandas."
  },
  {
    id: "evt_nyc_la_nacional",
    event_name: "La Nacional Friday Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-16",
    end_date: "2026-10-16",
    city: "New York",
    state: "NY",
    country_code: "US",
    address: "Spanish Benevolent Society, 239 W 14th St",
    price: "$28",
    is_free: false,
    source_url: "https://lanacionalmilonga.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:01:00Z",
    notes: "Iconic historic NYC Friday milonga running since 1999 in Chelsea."
  },
  {
    id: "evt_boston_malevaje",
    event_name: "Boston Milonga Malevaje",
    event_type: "MILONGA",
    start_date: "2026-10-24",
    end_date: "2026-10-24",
    city: "Boston",
    state: "MA",
    country_code: "US",
    address: "Dance Union Studio, 16 Bow St, Somerville",
    price: "$20",
    is_free: false,
    source_url: "https://bostontangomalevaje.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:02:00Z",
    notes: "Premier Boston monthly milonga with warm community atmosphere and wooden sprung floor."
  },
  {
    id: "evt_chicago_la_bruja",
    event_name: "Chicago La Bruja Autumn Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-07",
    end_date: "2026-11-07",
    city: "Chicago",
    state: "IL",
    country_code: "US",
    address: "ARTango Bistro & Ballroom, 4740 N Lincoln Ave",
    price: "$25",
    is_free: false,
    source_url: "https://artangochicago.com/milonga",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:03:00Z",
    notes: "Lincoln Square milonga featuring Argentine culinary delights and guest vinyl DJ."
  },
  {
    id: "evt_atlanta_la_ideal",
    event_name: "Atlanta Milonga La Ideal",
    event_type: "MILONGA",
    start_date: "2026-10-03",
    end_date: "2026-10-03",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Dancin' Ballroom, 1570 Holcomb Bridge Rd",
    price: "$20",
    is_free: false,
    source_url: "https://atlantatango.org/la-ideal",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:04:00Z",
    notes: "First Saturday monthly milonga in metro Atlanta with welcoming Southern hospitality."
  },
  {
    id: "evt_birmingham_magic_city",
    event_name: "Birmingham Magic City Tango Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-14",
    end_date: "2026-11-14",
    city: "Birmingham",
    state: "AL",
    country_code: "US",
    address: "The Dance Foundation Studio, 1715 27th Ct S, Homewood",
    price: "$18",
    is_free: false,
    source_url: "https://magiccitytango.org",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:05:00Z",
    notes: "Birmingham monthly community milonga connecting dancers across Alabama and the South."
  },
  {
    id: "evt_austin_esquina_tango",
    event_name: "Austin Esquina Tango Gran Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    city: "Austin",
    state: "TX",
    country_code: "US",
    address: "Esquina Tango Cultural Society, 209 Pedernales St",
    price: "$20",
    is_free: false,
    source_url: "https://esquinatango.org",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:06:00Z",
    notes: "East Austin vibrant community milonga celebrating Argentine culture and traditional cabeceo."
  },
  {
    id: "evt_dallas_oasis",
    event_name: "Dallas Oasis Saturday Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-31",
    end_date: "2026-10-31",
    city: "Dallas",
    state: "TX",
    country_code: "US",
    address: "Alpha Midway Dance Studio, 13740 Midway Rd",
    price: "$20",
    is_free: false,
    source_url: "https://dallastango.com/oasis",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:07:00Z",
    notes: "Dallas Fort-Worth premier social milonga with expansive dance floor and international tandas."
  },
  {
    id: "evt_tucson_desierto",
    event_name: "Tucson Milonga del Desierto",
    event_type: "MILONGA",
    start_date: "2026-11-06",
    end_date: "2026-11-08",
    city: "Tucson",
    state: "AZ",
    country_code: "US",
    address: "Movement Culture Studio, 610 N Swan Rd",
    price: "$35",
    is_free: false,
    source_url: "https://tucsontangosociety.org",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:08:00Z",
    notes: "Tucson desert autumn milonga weekend under Arizona stars with scenic mountain backdrop."
  },
  {
    id: "evt_seattle_century_ballroom",
    event_name: "Seattle Century Ballroom Friday Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-09",
    end_date: "2026-10-09",
    city: "Seattle",
    state: "WA",
    country_code: "US",
    address: "Century Ballroom, 915 E Pine St, Capitol Hill",
    price: "$22",
    is_free: false,
    source_url: "https://centuryballroom.com/tango",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:09:00Z",
    notes: "Historic 2,000 sq ft sprung hardwood ballroom on Capitol Hill with live orchestra set."
  },
  {
    id: "evt_la_corazon",
    event_name: "Milonga Corazón Los Angeles",
    event_type: "MILONGA",
    start_date: "2026-10-25",
    end_date: "2026-10-25",
    city: "Los Angeles",
    state: "CA",
    country_code: "US",
    address: "Candela La Brea Ballroom, 831 S La Brea Ave",
    price: "$25",
    is_free: false,
    source_url: "https://milongacorazonla.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:10:00Z",
    notes: "Long-running premier Sunday milonga in Mid-City LA with premier acoustics and top west coast DJs."
  },
  {
    id: "evt_sf_the_beat",
    event_name: "San Francisco The Beat Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-13",
    end_date: "2026-11-13",
    city: "San Francisco",
    state: "CA",
    country_code: "US",
    address: "Mission Cultural Center for Latino Arts, 2868 Mission St",
    price: "$22",
    is_free: false,
    source_url: "https://sftango.org/thebeat",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:11:00Z",
    notes: "Heart of the Mission district Friday milonga with rich bohemian tango energy."
  },
  {
    id: "evt_sd_tango_del_rey",
    event_name: "San Diego Tango Del Rey Saturday Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-21",
    end_date: "2026-11-21",
    city: "San Diego",
    state: "CA",
    country_code: "US",
    address: "Tango Del Rey, 3567 Del Rey St, Pacific Beach",
    price: "$20",
    is_free: false,
    source_url: "https://tangodelrey.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:12:00Z",
    notes: "San Diego's authentic Spanish-Moorish ballroom dedicated exclusively to Argentine tango."
  },
  {
    id: "evt_miami_sentimental",
    event_name: "Miami Sentimental Sunset Milonga",
    event_type: "MILONGA",
    start_date: "2026-12-05",
    end_date: "2026-12-05",
    city: "Miami",
    state: "FL",
    country_code: "US",
    address: "Doral Cultural Arts Center, 8363 NW 53rd St",
    price: "$25",
    is_free: false,
    source_url: "https://miamitangosociety.org",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:13:00Z",
    notes: "South Florida ocean breeze weekend milonga with Latin-American tango community."
  },

  // --- Canada Milongas ---
  {
    id: "evt_vancouver_central",
    event_name: "Vancouver Milonga Central",
    event_type: "MILONGA",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    city: "Vancouver",
    state: "BC",
    country_code: "CA",
    address: "Acadia Hall, 6361 University Blvd, Point Grey",
    price: "CAD $25",
    is_free: false,
    source_url: "https://vancouvertango.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:14:00Z",
    notes: "Pacific Northwest Saturday milonga attracting dancers from BC, Washington, and Oregon."
  },
  {
    id: "evt_toronto_mala_yunta",
    event_name: "Toronto Milonga Mala Yunta",
    event_type: "MILONGA",
    start_date: "2026-11-06",
    end_date: "2026-11-06",
    city: "Toronto",
    state: "ON",
    country_code: "CA",
    address: "The Continental Dance Club, 3141 Wharton Way",
    price: "CAD $25",
    is_free: false,
    source_url: "https://torontotango.com/malayunta",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:15:00Z",
    notes: "Premier Ontario Friday milonga with spacious floor, cozy lounge, and midnight empanadas."
  },
  {
    id: "evt_montreal_social_club",
    event_name: "Montreal Tango Social Club Sunday Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-18",
    end_date: "2026-10-18",
    city: "Montreal",
    state: "QC",
    country_code: "CA",
    address: "Tango Social Club, 5440 Rue Saint-Urbain, Mile End",
    price: "CAD $20",
    is_free: false,
    source_url: "https://tangosocialclub.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:16:00Z",
    notes: "Vibrant Mile End Sunday milonga immersed in Montreal's rich cultural and artistic vibe."
  },

  // --- Korea Milongas ---
  {
    id: "evt_seoul_onada_saturday",
    event_name: "Seoul Hongdae Tango O Nada Saturday Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-10",
    end_date: "2026-10-10",
    city: "Seoul",
    state: "Mapo-gu",
    country_code: "KR",
    address: "Tango O Nada, 396-14 Seogyo-dong, Mapo-gu",
    price: "₩15,000",
    is_free: false,
    source_url: "https://cafe.daum.net/tangoonada",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:17:00Z",
    notes: "Korea's most iconic long-running tango hall in Hongdae with 20+ years of tango tradition."
  },
  {
    id: "evt_seoul_eltango_friday",
    event_name: "Seoul Gangnam El Tango Friday Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-16",
    end_date: "2026-10-16",
    city: "Seoul",
    state: "Gangnam-gu",
    country_code: "KR",
    address: "El Tango Studio, Nonhyeon-dong 142-3, Gangnam-gu",
    price: "₩15,000",
    is_free: false,
    source_url: "https://eltango.kr",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:18:00Z",
    notes: "Gangnam prime milonga with immaculate sound setup and warm milonguero abrazo."
  },

  // --- China Milongas ---
  {
    id: "evt_beijing_sanlitun",
    event_name: "Beijing Sanlitun Gran Milonga",
    event_type: "MILONGA",
    start_date: "2026-10-24",
    end_date: "2026-10-24",
    city: "Beijing",
    state: "Chaoyang",
    country_code: "CN",
    address: "Sanlitun Soho Ballroom 3, Chaoyang District",
    price: "CNY 120",
    is_free: false,
    source_url: "https://beijingtango.org",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:19:00Z",
    notes: "Central Beijing Saturday milonga gathering top Chinese dancers and expat tango enthusiasts."
  },
  {
    id: "evt_shanghai_tangobang",
    event_name: "Shanghai Bund Tango Bang Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-14",
    end_date: "2026-11-14",
    city: "Shanghai",
    state: "Jing'an",
    country_code: "CN",
    address: "Bund 22 Grand Salon, 22 Zhongshan East 2nd Rd",
    price: "CNY 150",
    is_free: false,
    source_url: "https://tangobang.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:20:00Z",
    notes: "Prestigious weekend milonga overlooking Shanghai Huangpu River and the historic Bund."
  }
];

// Potential newly scraped events that the automated crawler finds from external tango feeds
export const CRAWLER_FEED_CANDIDATES: TangoEvent[] = [
  // --- USA Crawled Feeds ---
  {
    id: "crawler_evt_nyc_ensueno",
    event_name: "Ensueño Tango Salon Milonga NYC",
    event_type: "MILONGA",
    start_date: "2026-10-23",
    end_date: "2026-10-23",
    city: "New York",
    state: "NY",
    country_code: "US",
    address: "Ukrainian East Village Restaurant Ballroom, 140 2nd Ave",
    price: "$25",
    is_free: false,
    source_url: "https://ensuenotango.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:00:00Z",
    notes: "Historic East Village traditional salon milonga running every 4th Friday."
  },
  {
    id: "crawler_evt_boston_harvard",
    event_name: "Boston Harvard Square Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-08",
    end_date: "2026-11-08",
    city: "Boston",
    state: "MA",
    country_code: "US",
    address: "First Church Cambridge, 11 Garden St, Cambridge",
    price: "$20",
    is_free: false,
    source_url: "https://bostontangocalendar.com/harvard",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:01:00Z",
    notes: "University community milonga welcoming visiting dancers from around New England."
  },
  {
    id: "crawler_evt_chicago_nocturno",
    event_name: "Chicago Tango Nocturno Saturday Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-21",
    end_date: "2026-11-21",
    city: "Chicago",
    state: "IL",
    country_code: "US",
    address: "Dovetail Studios, 2853 W Montrose Ave",
    price: "$22",
    is_free: false,
    source_url: "https://chicagotangonocturno.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:02:00Z",
    notes: "Intimate late-night milonga with warm ambient lighting and curated Golden Age tandas."
  },
  {
    id: "crawler_evt_atlanta_sentimiento",
    event_name: "Atlanta Sentimiento Tango Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-28",
    end_date: "2026-11-28",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Academy Ballroom Atlanta, 800 Miami Cir NE",
    price: "$20",
    is_free: false,
    source_url: "https://atlantatango.org/sentimiento",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:03:00Z",
    notes: "Thanksgiving weekend social milonga with guest masterclasses and vinyl DJ."
  },
  {
    id: "crawler_evt_birmingham_vulcan",
    event_name: "Birmingham Vulcan Tango Milonga",
    event_type: "MILONGA",
    start_date: "2026-12-12",
    end_date: "2026-12-12",
    city: "Birmingham",
    state: "AL",
    country_code: "US",
    address: "Rosewood Dance Academy, 1929 3rd Ave N",
    price: "$18",
    is_free: false,
    source_url: "https://magiccitytango.org/vulcan",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:04:00Z",
    notes: "Alabama holiday edition milonga welcoming traveling dancers across the South."
  },
  {
    id: "crawler_evt_austin_corazon",
    event_name: "Austin Corazón de Tejas Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-14",
    end_date: "2026-11-14",
    city: "Austin",
    state: "TX",
    country_code: "US",
    address: "Corazón Latino Dance Studio, 500 W William Cannon Dr",
    price: "$20",
    is_free: false,
    source_url: "https://austintangosociety.org/corazon",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:05:00Z",
    notes: "Austin South Congress social milonga with live acoustic bandoneon performance."
  },
  {
    id: "crawler_evt_dallas_paloma",
    event_name: "Dallas Tango Society La Paloma Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-28",
    end_date: "2026-11-28",
    city: "Dallas",
    state: "TX",
    country_code: "US",
    address: "Contemporary Ballet Dallas, 5400 E Mockingbird Ln",
    price: "$20",
    is_free: false,
    source_url: "https://dallastangosociety.org/paloma",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:06:00Z",
    notes: "North Texas community milonga with Golden Era tandas and cabeceo etiquette."
  },
  {
    id: "crawler_evt_tucson_desert_rose",
    event_name: "Tucson Desert Rose Monthly Milonga",
    event_type: "MILONGA",
    start_date: "2026-12-19",
    end_date: "2026-12-19",
    city: "Tucson",
    state: "AZ",
    country_code: "US",
    address: "Tucson Movement Studio, 1920 E 10th St",
    price: "$18",
    is_free: false,
    source_url: "https://tucsontangosociety.org/desertrose",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:07:00Z",
    notes: "Cozy desert winter milonga with homemade sangria and empanadas."
  },
  {
    id: "crawler_evt_seattle_dance_underground",
    event_name: "Seattle Dance Underground Saturday Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-07",
    end_date: "2026-11-07",
    city: "Seattle",
    state: "WA",
    country_code: "US",
    address: "Dance Underground, 340 15th Ave E",
    price: "$20",
    is_free: false,
    source_url: "https://danceunderground.com/milonga",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:08:00Z",
    notes: "Beloved Capitol Hill tango sanctuary with supreme sound system and spring floor."
  },
  {
    id: "crawler_evt_la_malevaje",
    event_name: "Los Angeles Malevaje Hollywood Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-20",
    end_date: "2026-11-20",
    city: "Los Angeles",
    state: "CA",
    country_code: "US",
    address: "Hollywood Dance Center, 817 N Highland Ave",
    price: "$25",
    is_free: false,
    source_url: "https://latangocalendar.com/malevaje",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:09:00Z",
    notes: "Glamorous Hollywood Friday milonga with Argentine DJs and open dance floor."
  },
  {
    id: "crawler_evt_sf_genesis",
    event_name: "San Francisco Genesis Sunday Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-29",
    end_date: "2026-11-29",
    city: "San Francisco",
    state: "CA",
    country_code: "US",
    address: "Genesis Hall, 2550 18th St, Potrero Hill",
    price: "$20",
    is_free: false,
    source_url: "https://sftango.org/genesis",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:10:00Z",
    notes: "Potrero Hill Sunday afternoon social milonga bathed in natural daylight."
  },
  {
    id: "crawler_evt_sd_pacific",
    event_name: "San Diego Pacific Beach Seaside Milonga",
    event_type: "MILONGA",
    start_date: "2026-12-05",
    end_date: "2026-12-05",
    city: "San Diego",
    state: "CA",
    country_code: "US",
    address: "Crown Point Beach Pavilion, 3700 Crown Point Dr",
    price: "Free",
    is_free: true,
    source_url: "https://sandiegotangosociety.org/beach",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:11:00Z",
    notes: "Sunset outdoor seaside milonga on the bay under palm trees. Bring comfortable flat soles."
  },
  {
    id: "crawler_evt_miami_calle_ocho",
    event_name: "Miami Calle Ocho Tropical Milonga",
    event_type: "MILONGA",
    start_date: "2026-12-19",
    end_date: "2026-12-19",
    city: "Miami",
    state: "FL",
    country_code: "US",
    address: "Koubek Center Ballroom, 2705 SW 3rd St, Little Havana",
    price: "$25",
    is_free: false,
    source_url: "https://miamitangosociety.org/calleocho",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:12:00Z",
    notes: "Little Havana vibrant holiday milonga with live tropical tango ensemble."
  },

  // --- Canada Crawled Feeds ---
  {
    id: "crawler_evt_vancouver_underground",
    event_name: "Vancouver Tango Underground Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-21",
    end_date: "2026-11-21",
    city: "Vancouver",
    state: "BC",
    country_code: "CA",
    address: "Russian Community Centre, 2114 W 4th Ave, Kitsilano",
    price: "CAD $25",
    is_free: false,
    source_url: "https://vancouvertangounderground.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:13:00Z",
    notes: "Kitsilano monthly milonga with world-class wooden floor and visiting guest DJs."
  },
  {
    id: "crawler_evt_toronto_el_abrazo",
    event_name: "Toronto Milonga El Abrazo",
    event_type: "MILONGA",
    start_date: "2026-11-28",
    end_date: "2026-11-28",
    city: "Toronto",
    state: "ON",
    country_code: "CA",
    address: "Joy of Dance Centre, 95 Danforth Ave, Broadview",
    price: "CAD $22",
    is_free: false,
    source_url: "https://torontotango.com/elabrazo",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:14:00Z",
    notes: "Saturday night Danforth milonga celebrated for warm abrazo and friendly dancers."
  },
  {
    id: "crawler_evt_montreal_belle_epoque",
    event_name: "Montreal Milonga Belle Époque",
    event_type: "MILONGA",
    start_date: "2026-12-04",
    end_date: "2026-12-04",
    city: "Montreal",
    state: "QC",
    country_code: "CA",
    address: "Studio Tango Montréal, 7755 Boul. Saint-Laurent",
    price: "CAD $20",
    is_free: false,
    source_url: "https://studiotangomontreal.com/belleepoque",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:15:00Z",
    notes: "Chic Mile-Ex Friday milonga with Parisian-Buenos Aires bohemian ambiance."
  },

  // --- Korea Crawled Feeds (Seoul) ---
  {
    id: "crawler_evt_seoul_onada",
    event_name: "Seoul Hongdae Milonga O Nada",
    event_type: "MILONGA",
    start_date: "2026-10-30",
    end_date: "2026-10-30",
    city: "Seoul",
    state: "Mapo-gu",
    country_code: "KR",
    address: "Club O Nada, Wausan-ro 29-gil 4-3, Seogyo-dong",
    price: "₩15,000",
    is_free: false,
    source_url: "https://clubonada.kr",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:16:00Z",
    notes: "Legendary Hongdae tango club milonga, running since 2002. High energy dance floor."
  },
  {
    id: "crawler_evt_seoul_atango",
    event_name: "Seoul Gangnam A Tango Friday Grand Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-06",
    end_date: "2026-11-06",
    city: "Seoul",
    state: "Gangnam-gu",
    country_code: "KR",
    address: "A Tango Studio, Teheran-ro 14-gil 16, Yeoksam-dong",
    price: "₩18,000",
    is_free: false,
    source_url: "https://atangoseoul.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:17:00Z",
    notes: "Upscale Gangnam Friday milonga with premium sound system and strict floor navigation etiquette."
  },

  // --- China Crawled Feeds (Beijing, Shanghai) ---
  {
    id: "crawler_evt_beijing_sanlitun",
    event_name: "Beijing Sanlitun Milonga Tango Milonguero",
    event_type: "MILONGA",
    start_date: "2026-11-13",
    end_date: "2026-11-13",
    city: "Beijing",
    state: "Chaoyang",
    country_code: "CN",
    address: "Sanlitun SOHO Tower B, B1-528",
    price: "CNY 120",
    is_free: false,
    source_url: "https://beijingtangoclub.com/sanlitun",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:18:00Z",
    notes: "Friday social milonga in central Sanlitun popular with international tango travelers."
  },
  {
    id: "crawler_evt_shanghai_french_concession",
    event_name: "Shanghai French Concession Romantic Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-27",
    end_date: "2026-11-27",
    city: "Shanghai",
    state: "Xuhui",
    country_code: "CN",
    address: "Ferguson Lane Villa, 376 Wukang Rd, Xuhui District",
    price: "CNY 150",
    is_free: false,
    source_url: "https://shanghaitango.com/wukang",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:19:00Z",
    notes: "Art-Deco heritage villa milonga under French Concession sycamores with live piano & violin tanda."
  },

  // --- Duplicate Test Cases & International Feeds ---
  {
    id: "crawler_evt_miami_weekend",
    event_name: "Miami Sun & Tango Weekend",
    event_type: "FESTIVAL",
    start_date: "2026-12-11",
    end_date: "2026-12-14",
    city: "Miami",
    state: "FL",
    country_code: "US",
    address: "Deauville Oceanfront Hall, 6701 Collins Ave",
    price: "$195",
    is_free: false,
    source_url: "https://miamitangoweekend.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-05T20:00:00Z",
    notes: "Scraped from TangoMango & International Calendar feed."
  },
  {
    id: "crawler_evt_atlanta_dup_check",
    event_name: "Atlanta Tango Marathon 2026 Fall Edition",
    event_type: "MARATHON",
    start_date: "2026-10-15",
    end_date: "2026-10-18",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Westin Buckhead, 3391 Peachtree Rd NE",
    price: "$165",
    is_free: false,
    source_url: "https://atlantatangomarathon.com",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-05T20:01:00Z",
    notes: "DUPLICATE: Matches existing Atlanta event on same dates & city!"
  },
  // --- Weekly Crawler Feed: Atlanta & Birmingham Community Events ---
  {
    id: "crawler_evt_atlanta_tango_social_2nd_fri",
    event_name: "Atlanta Tango Social 2nd Friday Milonga",
    event_type: "MILONGA",
    start_date: "2026-11-13",
    end_date: "2026-11-13",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Dance Studio 27, 2768 E Ponce de Leon Ave, Decatur",
    price: "$15",
    is_free: false,
    source_url: "https://facebook.com/groups/atlantatangosocial",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:00:00Z",
    notes: "Crawled from Atlanta Tango Social Facebook community. Pre-milonga class with guest DJ tanda selections."
  },
  {
    id: "crawler_evt_birmingham_4th_sat",
    event_name: "Birmingham Fourth Saturday Milonga & Práctica",
    event_type: "MILONGA",
    start_date: "2026-11-28",
    end_date: "2026-11-28",
    city: "Birmingham",
    state: "AL",
    country_code: "US",
    address: "Formations Dance Studio, 1805 2nd Ave S, Birmingham",
    price: "$15",
    is_free: false,
    source_url: "https://facebook.com/groups/birminghamtango",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:00:00Z",
    notes: "Crawled from Birmingham Tango Alabama Facebook community. 4th Saturday social milonga."
  },
  {
    id: "crawler_evt_atlanta_winter_warmup",
    event_name: "Atlanta Winter Tango Weekend & Workshop",
    event_type: "FESTIVAL",
    start_date: "2026-12-04",
    end_date: "2026-12-06",
    city: "Atlanta",
    state: "GA",
    country_code: "US",
    address: "Academy Ballroom Atlanta, 800 Miami Cir NE",
    price: "$130",
    is_free: false,
    source_url: "https://facebook.com/events/atlantatangoevents",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T00:00:00Z",
    notes: "Crawled from Atlanta Argentine Tango Community Facebook calendar. 3-day weekend festival with master classes."
  },
  {
    id: "crawler_evt_tokyo_shibuya",
    event_name: "Tokyo Shibuya Friday Night Milonga & Práctica",
    event_type: "MILONGA",
    start_date: "2026-10-16",
    end_date: "2026-10-16",
    city: "Tokyo",
    state: "Tokyo",
    country_code: "JP",
    address: "Shibuya Cultural Center Owada, 23-21 Sakuragaokacho, Shibuya City",
    price: "¥2,500",
    is_free: false,
    source_url: "https://facebook.com/groups/tangotokyo",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:00:00Z",
    notes: "Popular weekly Tokyo social milonga with friendly welcome for traveling dancers."
  },
  {
    id: "crawler_evt_tokyo_roppongi_grand",
    event_name: "Tokyo Roppongi Grand Tango Encuentro & Workshop",
    event_type: "ENCUENTRO",
    start_date: "2026-11-20",
    end_date: "2026-11-22",
    city: "Tokyo",
    state: "Tokyo",
    country_code: "JP",
    address: "Roppongi Academy Hills, 6-10-1 Roppongi, Minato City",
    price: "¥5,000",
    is_free: false,
    source_url: "https://facebook.com/groups/tangotokyo",
    source_type: "AUTO_CRAWLED",
    status: "APPROVED",
    submitted_by: null,
    created_at: "2026-09-06T02:00:00Z",
    notes: "3-day autumn international tango gathering in Minato City, Tokyo."
  }
];
